#ATENÇÃO: Esse arquivo deve ficar na raiz do seu projeto
version: "3.3"

services:
  node:
    container_name: lilla-app
    build: ./.docker/node/
    tty: true
    ports:
      - 4200:4200
    volumes:
      - "./:/var/www/html"
    working_dir: /var/www/html
    command: > 
        bash -c "npm install && ng build --prod --outputHashing=all"
  #Caso queira criar um docker-compose de build, use esse comando: bash -c "npm install && ng serve --host 0.0.0.0"
  #ATENÇÃO: Manter o command acima, caso queira que ao subir o container esses comandos sejam rodados por padrão.
